name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dev dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]

      - name: Ruff Lint
        run: |
          ruff check .

      - name: Black Format Check
        run: |
          black --check .

      - name: Run Tests
        run: |
          pytest

